package com.swirlwave.android.proxies.clientside;

public enum ClientProtocolStateCode {
    UNKNOWN,
    CONNECT_ONION_PROXY,
    WRITE_ONION_PROXY_CONNECTION_REQUEST,
    READ_ONION_PROXY_CONNECTION_REQUEST_RESPONSE,
    READ_RANDOM_NUMBER_FROM_SERVER,
    WRITE_CONNECTION_MESSAGE_TO_SERVER, READ_CONNECTION_MESSAGE_RESPONSE, PROXYING
}
