package com.swirlwave.android.proxies.clientside;

public enum ClientProxyMode {
    UNKNOWN,
    AWAITING_ONIONPROXY_RESULT,
    INVALID_ONIONPROXY_RESULT,
    AWAITING_SERVERPROXY_RANDOM_NUMBER,
    AWAITING_SERVERPROXY_AUTHENTICATION_RESULT,
    REFUSED_BY_SERVERPROXY,
    ACCEPTING_PAYLOAD
}
